import { Inter, Roboto} from '@next/font/google'
import '/src/app/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({
  subsets: ['latin-ext'],
  weight: ['400', '500', '600', '700', '800']
}) 

const roboto = Roboto({
  subsets: ['latin-ext'],
  weight: '300'
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={''}>{children}</body>
    </html>
  )
}